import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Activity, Plus, Search, ShieldAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { discoverRoadSafetyCandidates } from "@/lib/incident-discovery.functions";

export const Route = createFileRoute("/_authenticated/admin/incident-sources")({
  head: () => ({ meta: [{ title: "Incident Sources: Share Barabara Admin" }] }),
  component: IncidentSourcesPage,
});

type Source = { id: string; name: string; base_url: string; source_class: string; keywords: string[]; enabled: boolean; check_interval_minutes: number; next_check_at: string; consecutive_failures: number; last_run_status: string | null; last_checked_at: string | null; last_success_at: string | null; last_failure_at: string | null; last_error: string | null; candidate_count: number };

function IncidentSourcesPage() {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ name: "", base_url: "https://", keywords: "road crash, highway closure", source_class: "unknown" });
  const queryKey = ["admin-incident-monitor-sources"];
  const sources = useQuery({ queryKey, queryFn: async () => { const { data, error } = await (supabase.from("incident_monitor_sources") as any).select("*").order("name"); if (error) throw error; return (data ?? []) as Source[]; } });
  const create = useMutation({ mutationFn: async () => { const keywords = form.keywords.split(",").map((value) => value.trim().slice(0, 180)).filter(Boolean).slice(0, 20); if (form.name.trim().length < 2 || !/^https:\/\//i.test(form.base_url.trim()) || !keywords.length) throw new Error("Enter a name, HTTPS source URL and at least one keyword."); const { data: auth } = await supabase.auth.getUser(); const { error } = await (supabase.from("incident_monitor_sources") as any).insert({ name: form.name.trim().slice(0, 160), base_url: form.base_url.trim(), source_class: form.source_class, keywords, check_interval_minutes: 60, next_check_at: new Date().toISOString(), created_by: auth.user?.id }); if (error) throw error; }, onSuccess: () => { setForm({ name: "", base_url: "https://", keywords: "road crash, highway closure", source_class: "unknown" }); toast.success("Monitored source added"); void queryClient.invalidateQueries({ queryKey }); }, onError: (error: Error) => toast.error(error.message) });
  const toggle = useMutation({ mutationFn: async ({ id, enabled }: { id: string; enabled: boolean }) => { const { error } = await (supabase.from("incident_monitor_sources") as any).update({ enabled }).eq("id", id); if (error) throw error; }, onSuccess: () => void queryClient.invalidateQueries({ queryKey }), onError: (error: Error) => toast.error(error.message) });
  const run = useMutation({ mutationFn: (sourceId: string) => discoverRoadSafetyCandidates({ data: { sourceId } }), onSuccess: (result) => { toast.success(result.inserted ? `${result.inserted} candidate draft${result.inserted === 1 ? "" : "s"} created` : "No new candidates found"); void queryClient.invalidateQueries({ queryKey }); }, onError: (error: Error) => toast.error(error.message || "Source check failed") });
  return <div className="space-y-6">
    <div><p className="text-xs font-semibold uppercase tracking-widest text-accent-foreground">Operations · Task 25</p><h1 className="mt-1 text-2xl font-extrabold">Incident sources</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Manage reviewed road-safety sources and bounded discovery checks. Retrieval creates evidence-backed drafts only; it never publishes an incident.</p></div>
    {sources.error ? <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-4 text-sm"><ShieldAlert className="mr-2 inline size-4" />Source operations are not active yet. Apply the additive incident source operations migration before adding monitored sources.</div> : null}
    <section className="rounded-lg border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-bold"><Plus className="size-4" />Add a monitored source</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm">Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" placeholder="Kenya National Highways Authority" /></label><label className="text-sm">HTTPS base URL<input value={form.base_url} onChange={(e) => setForm({ ...form, base_url: e.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" /></label><label className="text-sm">Keywords, comma separated<input value={form.keywords} onChange={(e) => setForm({ ...form, keywords: e.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3" /></label><label className="text-sm">Source class<select value={form.source_class} onChange={(e) => setForm({ ...form, source_class: e.target.value })} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3"><option value="official_authority">Official authority</option><option value="primary_source">Primary source</option><option value="reputable_secondary">Reputable secondary</option><option value="unknown">Unknown</option></select></label></div><Button className="mt-4" disabled={create.isPending || !!sources.error} onClick={() => create.mutate()}>{create.isPending ? "Adding…" : "Add source"}</Button></section>
    <section className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Configured sources</h2>{sources.isLoading ? <p className="mt-4 text-sm text-muted-foreground">Loading source operations…</p> : null}<div className="mt-4 space-y-3">{sources.data?.map((source) => <article key={source.id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{source.name}</h3><a className="text-xs text-brand-blue underline" href={source.base_url} target="_blank" rel="noopener noreferrer">{source.base_url}</a><p className="mt-1 text-xs text-muted-foreground">{source.source_class} · every {source.check_interval_minutes} minutes · {source.keywords.join(", ")}</p></div><span className={`rounded-full px-2 py-1 text-xs ${source.enabled ? "bg-safe/15 text-safe" : "bg-muted text-muted-foreground"}`}>{source.enabled ? "Enabled" : "Disabled"}</span></div><div className="mt-3 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2 lg:grid-cols-4"><span>Last checked: {source.last_checked_at ? new Date(source.last_checked_at).toLocaleString("en-KE", { timeZone: "Africa/Nairobi" }) : "Never"}</span><span>Next eligible: {source.next_check_at ? new Date(source.next_check_at).toLocaleString("en-KE", { timeZone: "Africa/Nairobi" }) : "Due now"}</span><span>Run: {source.last_run_status ?? "Never"} · failures {source.consecutive_failures}</span><span>Candidate drafts: {source.candidate_count}</span></div>{source.last_error ? <p className="mt-2 rounded bg-destructive/5 p-2 text-xs text-destructive">Last failure: {source.last_error}</p> : null}<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!source.enabled || run.isPending} onClick={() => run.mutate(source.id)}><Search className="mr-1 size-3" />{run.isPending ? "Checking…" : "Check source now"}</Button><Button size="sm" variant="ghost" disabled={toggle.isPending} onClick={() => toggle.mutate({ id: source.id, enabled: !source.enabled })}>{source.enabled ? "Disable" : "Enable"}</Button></div></article>)}{!sources.isLoading && !sources.error && !sources.data?.length ? <p className="rounded border border-dashed border-border p-4 text-sm text-muted-foreground">No monitored sources configured yet.</p> : null}</div></section>
    <div className="flex items-center gap-2 text-xs text-muted-foreground"><Activity className="size-4" />External retrieval remains fail-closed when the configured provider is unavailable. Review candidates in the Incident Discovery queue.</div>
  </div>;
}
