import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { discoverRoadSafetyCandidates } from "@/lib/incident-discovery.functions";
import { toast } from "sonner";

export function IncidentDiscoveryPanel() {
  const queryClient = useQueryClient();
  const queryKey = ["admin-incident-discovery-candidates"];
  const candidates = useQuery({ queryKey, queryFn: async () => { const { data, error } = await (supabase.from("incident_discovery_candidates") as any).select("*").eq("status", "draft").order("created_at", { ascending: false }).limit(30); if (error) throw error; return data ?? []; } });
  const scan = useMutation({ mutationFn: () => discoverRoadSafetyCandidates({ data: {} }), onSuccess: (result) => { toast.success(result.inserted ? `${result.inserted} discovery draft${result.inserted === 1 ? "" : "s"} created` : "No new candidates found"); void queryClient.invalidateQueries({ queryKey }); }, onError: (error: Error) => toast.error(error.message || "External discovery is unavailable right now.") });
  const resolve = useMutation({ mutationFn: async ({ id, status }: { id: string; status: "rejected" | "merged" }) => { const { data: auth } = await supabase.auth.getUser(); const { error } = await (supabase.from("incident_discovery_candidates") as any).update({ status, reviewed_by: auth.user?.id ?? null, reviewed_at: new Date().toISOString(), review_notes: status === "rejected" ? "Rejected during staff review." : "Marked for merge follow-up during staff review." }).eq("id", id); if (error) throw error; }, onSuccess: () => { toast.success("Discovery draft updated"); void queryClient.invalidateQueries({ queryKey }); }, onError: (error: Error) => toast.error(error.message) });
  return <section className="mt-8 rounded-lg border border-border bg-card p-5 card-elevated" aria-labelledby="incident-discovery-heading"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="incident-discovery-heading" className="flex items-center gap-2 font-bold"><ShieldAlert className="size-5 text-accent" /> External incident discovery</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Scans the configured retrieval provider for possible road-safety developments. Results are untrusted admin drafts and never publish automatically.</p></div><Button type="button" variant="outline" disabled={scan.isPending} onClick={() => scan.mutate()}><Search className="mr-2 size-4" />{scan.isPending ? "Scanning…" : "Scan sources"}</Button></div>{candidates.error ? <p className="mt-4 rounded border border-dashed border-border p-3 text-sm text-muted-foreground">Discovery is unavailable until a reviewed external search provider is configured.</p> : null}{candidates.isLoading ? <p className="mt-4 text-sm text-muted-foreground">Loading discovery drafts…</p> : null}<div className="mt-4 space-y-3">{candidates.data?.map((candidate: any) => <article key={candidate.id} className="rounded border border-border p-3"><a href={candidate.source_url} target="_blank" rel="noopener noreferrer" className="font-semibold text-brand-blue underline">{candidate.source_title}</a><p className="mt-1 text-xs text-muted-foreground">{candidate.source_organization ?? "External source"} · {candidate.incident_type ?? "incident"}</p><p className="mt-2 text-sm text-foreground/90">{candidate.source_excerpt}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="ghost" onClick={() => resolve.mutate({ id: candidate.id, status: "rejected" })}>Reject draft</Button><Button size="sm" variant="outline" onClick={() => resolve.mutate({ id: candidate.id, status: "merged" })}>Mark reviewed / merge later</Button></div></article>)}{!candidates.isLoading && !candidates.error && !candidates.data?.length ? <p className="rounded border border-dashed border-border p-4 text-sm text-muted-foreground">No discovery drafts awaiting review.</p> : null}</div></section>;
}
