import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Search, ShieldAlert, Link2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { discoverRoadSafetyCandidates } from "@/lib/incident-discovery.functions";
import { toast } from "sonner";

const labels: Record<string, string> = { alert: "Alert", report: "Accident report", feed_post: "Feed post", discovery_candidate: "Discovery draft" };

export function IncidentDiscoveryPanel() {
  const queryClient = useQueryClient();
  const [canonicalIds, setCanonicalIds] = useState<Record<string, string>>({});
  const queryKey = ["admin-incident-discovery-candidates"];
  const candidates = useQuery({ queryKey, queryFn: async () => { const { data, error } = await (supabase.from("incident_discovery_candidates") as any).select("*").eq("status", "draft").order("created_at", { ascending: false }).limit(30); if (error) throw error; return data ?? []; } });
  const suggestions = useQuery({ queryKey: ["admin-incident-duplicate-suggestions"], queryFn: async () => { const { data, error } = await (supabase.from("incident_duplicate_suggestions") as any).select("*").eq("status", "suggested").order("confidence", { ascending: false }).limit(50); if (error) throw error; return data ?? []; } });
  const suggestionDetails = useQuery({ queryKey: ["admin-incident-duplicate-suggestion-details", (suggestions.data ?? []).map((item: any) => item.id).join(",")], enabled: Boolean(suggestions.data?.length), queryFn: async () => { const items = suggestions.data ?? []; const ids = (type: string) => items.filter((item: any) => item.candidate_type === type || item.target_type === type).flatMap((item: any) => [item.candidate_id, item.target_id]); const [alerts, reports, feed, drafts] = await Promise.all([supabase.from("alerts").select("id,title,county").in("id", ids("alert")), supabase.from("accident_reports").select("id,title,county").in("id", ids("report")), supabase.from("feed_posts").select("id,body").in("id", ids("feed_post")), (supabase.from("incident_discovery_candidates") as any).select("id,source_title,source_url").in("id", ids("discovery_candidate"))]); const map = new Map<string, any>(); for (const row of [...(alerts.data ?? []), ...(reports.data ?? []), ...(feed.data ?? []), ...(drafts.data ?? [])]) map.set(row.id, row); return map; } });
  const canonicalReports = useQuery({ queryKey: ["admin-approved-reports-for-discovery"], queryFn: async () => { const { data, error } = await supabase.from("accident_reports").select("id,title,county,occurred_at").eq("status", "approved").order("occurred_at", { ascending: false }).limit(200); if (error) throw error; return data ?? []; } });
  const scan = useMutation({ mutationFn: () => discoverRoadSafetyCandidates({ data: {} }), onSuccess: (result) => { toast.success(result.inserted ? `${result.inserted} discovery draft${result.inserted === 1 ? "" : "s"} created` : "No new candidates found"); void queryClient.invalidateQueries({ queryKey }); void queryClient.invalidateQueries({ queryKey: ["admin-incident-duplicate-suggestions"] }); }, onError: (error: Error) => toast.error(error.message || "External discovery is unavailable right now.") });
  const resolveCandidate = useMutation({ mutationFn: async ({ id, status, canonicalId }: { id: string; status: "rejected" | "merged"; canonicalId?: string }) => { const { data: auth } = await supabase.auth.getUser(); if (status === "merged" && !canonicalId) throw new Error("Choose the approved canonical incident first"); const { error } = await (supabase.from("incident_discovery_candidates") as any).update({ status, duplicate_of_report_id: canonicalId ?? null, reviewed_by: auth.user?.id ?? null, reviewed_at: new Date().toISOString(), review_notes: status === "rejected" ? "Rejected during staff review." : "Linked to the selected canonical incident during staff review." }).eq("id", id).eq("status", "draft"); if (error) throw error; }, onSuccess: () => { toast.success("Discovery draft updated"); void queryClient.invalidateQueries({ queryKey }); }, onError: (error: Error) => toast.error(error.message) });
  const resolveSuggestion = useMutation({ mutationFn: async ({ id, status }: { id: string; status: "confirmed" | "not_duplicate" }) => { const { data: auth } = await supabase.auth.getUser(); const { error } = await (supabase.from("incident_duplicate_suggestions") as any).update({ status, reviewed_by: auth.user?.id ?? null, reviewed_at: new Date().toISOString(), review_note: status === "confirmed" ? "Confirmed during staff duplicate review." : "Rejected as a false positive during staff duplicate review." }).eq("id", id).eq("status", "suggested"); if (error) throw error; }, onSuccess: () => { toast.success("Duplicate suggestion reviewed"); void queryClient.invalidateQueries({ queryKey: ["admin-incident-duplicate-suggestions"] }); }, onError: (error: Error) => toast.error(error.message) });
  const suggestionFor = (id: string) => (suggestions.data ?? []).find((item: any) => item.candidate_type === "discovery_candidate" && item.candidate_id === id);

  return <section className="mt-8 rounded-lg border border-border bg-card p-5 card-elevated" aria-labelledby="incident-discovery-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="incident-discovery-heading" className="flex items-center gap-2 font-bold"><ShieldAlert className="size-5 text-accent" /> External incident discovery</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Scans configured providers for untrusted drafts. Cross-content matches are suggestions only and never publish automatically, merge or delete records.</p></div><Button type="button" variant="outline" disabled={scan.isPending} onClick={() => scan.mutate()}><Search className="mr-2 size-4" />{scan.isPending ? "Scanning…" : "Scan sources"}</Button></div>
    {candidates.error ? <p className="mt-4 rounded border border-dashed border-border p-3 text-sm text-muted-foreground">Discovery is unavailable until a reviewed external search provider is configured.</p> : null}
    {suggestions.error ? <p className="mt-3 rounded border border-dashed border-border p-3 text-sm text-muted-foreground">Cross-content duplicate review requires the additive duplicate-suggestions migration. Existing discovery review remains available.</p> : null}
    {suggestions.data?.length ? <div className="mt-5 space-y-3"><h3 className="font-semibold">Cross-content duplicate suggestions</h3>{suggestions.data.map((item: any) => { const candidate = suggestionDetails.data?.get(item.candidate_id); const target = suggestionDetails.data?.get(item.target_id); const link = (type: string, id: string) => type === "alert" ? `/alerts/${id}` : type === "report" ? `/reports/${id}` : type === "discovery_candidate" ? (target?.source_url ?? "#") : "/feed"; return <article key={item.id} className="rounded border border-amber-200 bg-amber-50/50 p-3"><p className="text-sm font-semibold">{labels[item.candidate_type] ?? item.candidate_type} <span className="font-normal text-muted-foreground">→</span> {labels[item.target_type] ?? item.target_type}</p><div className="mt-1 grid gap-1 text-sm sm:grid-cols-2"><a className="underline" href={link(item.candidate_type, item.candidate_id)} target={item.candidate_type === "discovery_candidate" ? "_blank" : undefined} rel="noopener noreferrer">{candidate?.title ?? candidate?.source_title ?? candidate?.body?.slice(0, 100) ?? "Candidate record"}</a><a className="underline" href={link(item.target_type, item.target_id)} target={item.target_type === "discovery_candidate" ? "_blank" : undefined} rel="noopener noreferrer">{target?.title ?? target?.source_title ?? target?.body?.slice(0, 100) ?? "Suggested canonical record"}</a></div><p className="mt-1 text-sm">{Math.round(Number(item.confidence) * 100)}% confidence · {Array.isArray(item.reasons) ? item.reasons.join(" · ") : "Evidence available in the linked records."}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => resolveSuggestion.mutate({ id: item.id, status: "confirmed" })}><Link2 className="mr-1 size-3" />Confirm/link</Button><Button size="sm" variant="ghost" onClick={() => resolveSuggestion.mutate({ id: item.id, status: "not_duplicate" })}><XCircle className="mr-1 size-3" />Not duplicate</Button></div></article>; })}</div> : null}
    {candidates.isLoading ? <p className="mt-4 text-sm text-muted-foreground">Loading discovery drafts…</p> : null}
    <div className="mt-4 space-y-3">{candidates.data?.map((candidate: any) => { const suggestion = suggestionFor(candidate.id); return <article key={candidate.id} className="rounded border border-border p-3"><a href={candidate.source_url} target="_blank" rel="noopener noreferrer" className="font-semibold text-brand-blue underline">{candidate.source_title}</a><p className="mt-1 text-xs text-muted-foreground">{candidate.source_organization ?? "External source"} · {candidate.incident_type ?? "incident"}</p>{candidate.location_hint ? <p className="mt-1 text-xs text-muted-foreground">Possible location: {candidate.location_hint}</p> : null}{suggestion ? <p className="mt-1 text-xs font-semibold text-amber-700">Cross-content suggestion: {labels[suggestion.target_type] ?? suggestion.target_type} ({Math.round(Number(suggestion.confidence) * 100)}%).</p> : candidate.duplicate_of_report_id ? <p className="mt-1 text-xs font-semibold text-amber-700">Possible duplicate of an approved report{candidate.duplicate_confidence ? ` (${Math.round(candidate.duplicate_confidence * 100)}% confidence)` : ""}. Review before linking.</p> : null}<p className="mt-2 text-sm text-foreground/90">{candidate.source_excerpt}</p><div className="mt-3 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto_auto]"><select aria-label={`Canonical incident for ${candidate.source_title}`} value={canonicalIds[candidate.id] ?? ""} onChange={(event) => setCanonicalIds((current) => ({ ...current, [candidate.id]: event.target.value }))} className="h-9 rounded-md border border-input bg-background px-2 text-sm"><option value="">Choose approved canonical incident</option>{(canonicalReports.data ?? []).map((report) => <option key={report.id} value={report.id}>{report.title} · {report.county}</option>)}</select><Button size="sm" variant="ghost" onClick={() => resolveCandidate.mutate({ id: candidate.id, status: "rejected" })}>Reject draft</Button><Button size="sm" variant="outline" disabled={!canonicalIds[candidate.id] || resolveCandidate.isPending} onClick={() => resolveCandidate.mutate({ id: candidate.id, status: "merged", canonicalId: canonicalIds[candidate.id] })}>Link to canonical</Button></div></article>; })}{!candidates.isLoading && !candidates.error && !candidates.data?.length ? <p className="rounded border border-dashed border-border p-4 text-sm text-muted-foreground">No discovery drafts awaiting review.</p> : null}</div>
  </section>;
}
